### ISSUE TITLE
Previous/back button functionality

### ISSUE THREAD

**Issue by JayUK** [apondman/MediaBrowser#27]
MePo is configured to jump direct to movies-all and tvshows-all from the home page - this works a treat. But the issue is when I press back/previous on the remote, I would have hoped it would have gone back to the screen I jumped direct to (eg movies-all), but instead it jumps back through all the previous MB plugin selections and screens (so if I have been clicking/selecting movies/shows in the plugin, the previous/back button jumps me to their selection as opposed to return me back out the plugin, so its not a "clean" one or two click to get back to the home screen

**Comment by apondman** [comment]
Correct currently I only implemented a back command that will back track your path untill you leave the entry point.
I can easily change that into the following MediaPortal defaults:

Exit to parent item = ACTION_PARENT_DIR          (Key: U by default)
Exit from window = ACTION_PREVIOUS_MENU    (Key: ESC by default)

exiting from the window would remember where you left off when you return.
More suggestions are welcome
