### ISSUE TITLE
Unable to launch remotely from MBS

### ISSUE THREAD

**Issue by saitoh183** [apondman/MediaBrowser#35]
launching a video from MBS to Mediaportal will cause MP to hang on a blank screen. This didnt happen on the last version.

Dont know if its the addon in combination with the latest server update.

**Comment by apondman** [comment]
Just checked on my setup and i don't have the issue. Can you elaborate on the issue? Does it happen with every file?

**Comment by saitoh183** [comment]
Right now yes. I open MBS on my laptop and do a remote launch and send it to MEdiaportal, MP will change screen as if it will start and just hangs with the titan background.

**Comment by saitoh183** [comment]
Updated to 1.7pre MP and its still the same issue. I checked the show psych and i have 10 eps for season 8 but i only see 1 to 9
![capture](https://f.cloud.github.com/assets/1534197/2520527/83e97028-b48d-11e3-9618-e6da52666e3e.JPG)

![capture1](https://f.cloud.github.com/assets/1534197/2520528/8dcad2c6-b48d-11e3-94fe-f19141a1cb94.JPG)

As for if its with all shows, the answer is no....but it will happen to random shows. Like it happened for Family guy and after i watched it using Mediabrowser classic, it showed up like 3 days later out of the blue. dont know if another episode addition from another show triggered a refresh or something.

**Comment by Pogman** [comment]
This has happened to me too on my network client, sometimes it will hang MP or it will start the video and not go fullscreen but sit on the details screen.

Not seen this issue if I'm on the server PC.

**Comment by saitoh183** [comment]
Yeah dont have the hang issue anymore since 1.7.1 hotfix... but still have the issue above with not all episodes showing up

**Comment by apondman** [comment]
i'm going to close this issue and make a new one for the missing episodes.
