### ISSUE TITLE
sort is broken

### ISSUE THREAD

**Issue by ncoH** [apondman/MediaBrowser#52]
The sortby option only sorts by name. All others doesn`t work.
Perhaps related to wrong "on next" episodes sort.

The latest movie/episode list sorts right.

**Comment by apondman** [comment]
so what is broken exactly? the sort on a specific view?

**Comment by ncoH** [comment]
It`s broken in every view. All sort options sort by name. Only the "recently added" view sorts automatically by "date added"

**Comment by apondman** [comment]
I see something broke indeed. Fixing it now ;)
